// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzgxikfnnxmwjoakzdqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16Z3hpa2Zubnhtd2pvYWt6ZHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzE2MjYsImV4cCI6MjA2NTQwNzYyNn0.eaw1Ak2RxlK35lpLYEHZqB2UosAhgWfT26Wyk2F4SQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);